spring.application.name=msv-clientes

spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

eureka.client.service-url.defautlzone=http://localhost:8791/eureka
eureka.instance.instance-id=${spring.application.name}:${random.value}
server.port=8081


